### PR TITLE
Add green fill for hidden items

### PR DESCRIPTION
**Pull request by tootster**
Add a green fill to hidden items, It will add a bright green fill with 50% transparency

### CODE REVIEW

**Comment by tootster** [comment]
Sorry if I did this wrong I suck at git <3

**Comment by f3rked** [comment]
Thanks for adding this - I'll take a look and test it out tomorrow.

**Comment by f3rked** [comment]
I think for this to not disappear when cams are switched or if someone turns this on when not on a cam, you'll need to add the function call in the observer [here](https://github.com/f3rked/maej3rked-tools/blob/9456a2dfd441aed80cb27a55a59d673b628024a2/src/modules/observers.js#L163)

**Comment by tootster** [comment]
Gave it a test run and its working fine when: switching cams, exiting to the homepage then going back to a cam and going anywhere else on the site and switching back to a cam. You can also turn it on from anywhere on the site with no issues. Seems to only break when the page is refreshed. Just forgot to call it as part of startup.

**Comment by f3rked** [comment]
strange, the first time i enabled it off cam and it wasn't showing up - i had to disable and reenable for it to show up.  but after the first time, that hasn't happened again.  not sure if i hallucinated it or what.

if you add `toggleHiddenItems(config.get("showHiddenItems"));` [here](https://github.com/f3rked/maej3rked-tools/blob/9456a2dfd441aed80cb27a55a59d673b628024a2/src/modules/functions.js#L1111), it should then work properly on page refresh too.

also could you remove the updates to the user script and package files - i'll handle bumping the version

**Pull request closed without merging**
